# Generated by Django 4.2.6 on 2023-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_les_02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='str', upload_to='hw_les_02'),
            preserve_default=False,
        ),
    ]
